### ISSUE TITLE
a sample user would be nice

### ISSUE THREAD

**Issue by ffischer1984** [ryanfb/okc-leak-checker#1]
so everyone can check that this site works correctly ;)

**Comment by ryanfb** [comment]
I didn't want to disclose the username of any specific user, so I've added the synthetic username `example_user` to the username table for this purpose. I can tell you that I've spot checked random usernames from the dump, and seen people say that they've found themselves in the data dump based on this site. There was a bug early on with 150 usernames that had encoded characters (e.g. `<e9>` for `é`), I went through and unescaped these and added them to the (hashed) username table on the morning of May 14th.
